[v1]
"bat 0.24.0 (registry+https://github.com/rust-lang/crates.io-index)" = ["bat"]
"cargo-audit 0.17.6 (registry+https://github.com/rust-lang/crates.io-index)" = ["cargo-audit"]
"cargo-binstall 1.5.0 (registry+https://github.com/rust-lang/crates.io-index)" = ["cargo-binstall"]
"cargo-cache 0.8.3 (registry+https://github.com/rust-lang/crates.io-index)" = ["cargo-cache"]
"cargo-depgraph 1.5.0 (registry+https://github.com/rust-lang/crates.io-index)" = ["cargo-depgraph"]
"cargo-expand 1.0.79 (registry+https://github.com/rust-lang/crates.io-index)" = ["cargo-expand"]
"cargo-geiger 0.11.6 (registry+https://github.com/rust-lang/crates.io-index)" = ["cargo-geiger"]
"cargo-hack 0.6.15 (registry+https://github.com/rust-lang/crates.io-index)" = ["cargo-hack"]
"cargo-lambda 1.0.3 (registry+https://github.com/rust-lang/crates.io-index)" = ["cargo-lambda"]
"cargo-machete 0.5.0 (registry+https://github.com/rust-lang/crates.io-index)" = ["cargo-machete"]
"cargo-sort 1.0.9 (registry+https://github.com/rust-lang/crates.io-index)" = ["cargo-sort"]
"cargo-unused-features 0.2.0 (registry+https://github.com/rust-lang/crates.io-index)" = ["unused-features"]
"cargo-update 13.0.4 (registry+https://github.com/rust-lang/crates.io-index)" = [
    "cargo-install-update",
    "cargo-install-update-config",
]
"cargo-watch 8.4.0 (registry+https://github.com/rust-lang/crates.io-index)" = ["cargo-watch"]
"erdtree 3.1.2 (registry+https://github.com/rust-lang/crates.io-index)" = ["erd"]
"evcxr_repl 0.15.0 (registry+https://github.com/rust-lang/crates.io-index)" = ["evcxr"]
"flamegraph 0.6.3 (registry+https://github.com/rust-lang/crates.io-index)" = [
    "cargo-flamegraph",
    "flamegraph",
]
"hyperfine 1.17.0 (registry+https://github.com/rust-lang/crates.io-index)" = ["hyperfine"]
"just 1.14.0 (registry+https://github.com/rust-lang/crates.io-index)" = ["just"]
"opis 0.4.0 (path+file:///home/gilgamesh/projects/hivo-app/opis)" = ["opis"]
"parallel-disk-usage 0.9.0 (registry+https://github.com/rust-lang/crates.io-index)" = ["pdu"]
"tere 1.4.0 (registry+https://github.com/rust-lang/crates.io-index)" = ["tere"]
"tokei 12.1.2 (registry+https://github.com/rust-lang/crates.io-index)" = ["tokei"]
"wthrr 1.1.1 (registry+https://github.com/rust-lang/crates.io-index)" = ["wthrr"]
"typos-cli 1.21.0 (registry+https://github.com/rust-lang/crates.io-index)" = ["typos"]
"cargo-nextest 0.9.78 (registry+https://github.com/rust-lang/crates.io-index)" = ["cargo-nextest"]
"git-delta 0.18.2 (registry+https://github.com/rust-lang/crates.io-index)" = ["delta"]
"fd-find 10.2.0 (registry+https://github.com/rust-lang/crates.io-index)" = ["fd"]
"jj-cli 0.22.0 (registry+https://github.com/rust-lang/crates.io-index)" = ["jj"]
